Issue 532; https://github.com/mdboom/matplotlib/commit/81068e9967387ea69133277242a9804d646ea4ef
diff -ur matplotlib-1.2.0.orig/src/ft2font.cpp matplotlib-1.2.0/src/ft2font.cpp
--- src/ft2font.cpp	2012-10-31 08:11:14.000000000 +0800
+++ src/ft2font.cpp	2012-11-29 11:09:43.569808461 +0800
@@ -852,28 +852,24 @@
     {
         std::ostringstream s;
         s << "Could not load facefile " << facefile << "; Unknown_File_Format" << std::endl;
-        ob_refcnt--;
         throw Py::RuntimeError(s.str());
     }
     else if (error == FT_Err_Cannot_Open_Resource)
     {
         std::ostringstream s;
         s << "Could not open facefile " << facefile << "; Cannot_Open_Resource" << std::endl;
-        ob_refcnt--;
         throw Py::RuntimeError(s.str());
     }
     else if (error == FT_Err_Invalid_File_Format)
     {
         std::ostringstream s;
         s << "Could not open facefile " << facefile << "; Invalid_File_Format" << std::endl;
-        ob_refcnt--;
         throw Py::RuntimeError(s.str());
     }
     else if (error)
     {
         std::ostringstream s;
         s << "Could not open facefile " << facefile << "; freetype error code " << error << std::endl;
-        ob_refcnt--;
         throw Py::RuntimeError(s.str());
     }
 
@@ -891,7 +887,6 @@
     {
         std::ostringstream s;
         s << "Could not set the fontsize for facefile  " << facefile << std::endl;
-        ob_refcnt--;
         throw Py::RuntimeError(s.str());
     }
 
